# syntax=docker/dockerfile:experimental
#############
### build ###
#############
FROM golang as builder

ADD . /go/src/git.dsg.tuwien.ac.at/mc2/go-telemetry
WORKDIR /go/src/git.dsg.tuwien.ac.at/mc2/go-telemetry
RUN CGO_ENABLED=0 GOARCH=arm GOARM=7 go build -v -o /usr/local/bin/telemd cmd/telemd/main.go

#############
### prod ###
#############
FROM arm32v7/alpine
COPY --from=builder /usr/local/bin /usr/local/bin

ENTRYPOINT telemd
